# Generated by Django 5.2 on 2025-04-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_remove_order_delivered_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
